name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      NEON_TEST_DB_URL: ${{ secrets.NEON_TEST_DB_URL }}
      NEON_MAIN_DB_URL: ${{ secrets.NEON_TEST_DB_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Test database connection
        run: |
          echo "Testing database connection..."
          python -c "
          import os
          import psycopg
          try:
              conn = psycopg.connect(os.getenv('NEON_TEST_DB_URL'))
              print('✅ Database connection successful')
              conn.close()
          except Exception as e:
              print(f'❌ Database connection failed: {e}')
              exit(1)
          "


      - name: Run tests
        run: |
          pytest test.py -v