name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_URL: ${{ secrets.TEST_DB_URL}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for Neon DB to wake up
        run: |
          echo "Waiting for Neon DB..."
          for i in {1..10}; do
            pg_isready -d "$NEON_TEST_DB_URL" && break
            echo "Still waiting..."
            sleep 5
          done

      - name: Run tests
        run: |
          pytest test.py -v