name: CI Run test

on:
  push:
    branch: [main]
  pull_request:

jobs:
  runs-on: ubuntu-latest

  test:
    services:
      postgres:
        image: postgres:13

        env:
          POSTGRES_USER: ${{ TEST_DB_USER}}
          POSTGRES_PASSWORD: ${{ TEST_DB_PASSWORD}}
          POSTGRES_DB: ${{ TEST_DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-delay 5s
          --health-retries 5

  env:
      DB_USERNAME: ${{ TEST_DB_USER }}
      DB_PASSWORD: ${{ TEST_DB_PASSWORD }}
      DB_HOST: ${{ TEST_DB_HOST }}
      DB_PORT: ${{ TEST_DB_PORT }}
      DB_NAME: ${{ TEST_DB_NAME }}
      SECRET_KEY: ${{ SECRET_KEY}}

  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python pip --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    


          

